/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Isaac
 */
public class frmUsingStringMethods extends javax.swing.JFrame {

    /**
     * Creates new form frmUsingStringMethods
     */
    public frmUsingStringMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblInstLength = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        btnLength = new javax.swing.JButton();
        lblLengthValue = new javax.swing.JLabel();
        lblInstToUpper = new javax.swing.JLabel();
        txtToUpper = new javax.swing.JTextField();
        btnToUpper = new javax.swing.JButton();
        lblToUpperValue = new javax.swing.JLabel();
        lblInstCharAt = new javax.swing.JLabel();
        txtCharAt = new javax.swing.JTextField();
        btnCharAt = new javax.swing.JButton();
        lblCharAtValue = new javax.swing.JLabel();
        lblInstIdentical = new javax.swing.JLabel();
        txtIdentical1 = new javax.swing.JTextField();
        txtIdentical2 = new javax.swing.JTextField();
        btnIdentical = new javax.swing.JButton();
        lblIdenticalValue = new javax.swing.JLabel();
        lblInstIndexOf = new javax.swing.JLabel();
        txtIndexOf1 = new javax.swing.JTextField();
        txtIndexOf2 = new javax.swing.JTextField();
        btnIndexOf = new javax.swing.JButton();
        lblIndexOfValue = new javax.swing.JLabel();
        lblInstCharAtMultiple = new javax.swing.JLabel();
        txtCharAtMultiple = new javax.swing.JTextField();
        btnCharAtMultiple = new javax.swing.JButton();
        lblCharAtMultipleValue = new javax.swing.JLabel();
        lblInstReplace = new javax.swing.JLabel();
        txtReplace = new javax.swing.JTextField();
        btnReplace = new javax.swing.JButton();
        lblReplaceValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        lblHeader.setText("Super String Software");

        lblInstLength.setText("Enter a string. The program will output the number of characters in that string.");

        btnLength.setText("Length");
        btnLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLengthActionPerformed(evt);
            }
        });

        lblInstToUpper.setText("Enter a string using lowercase letters. The program will output the string in all capital letters.");

        btnToUpper.setText("All Caps");
        btnToUpper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToUpperActionPerformed(evt);
            }
        });

        lblInstCharAt.setText("Enter a string. The prorgam will outptut the character at the fourth spot.");

        btnCharAt.setText("4th Spot");
        btnCharAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCharAtActionPerformed(evt);
            }
        });

        lblInstIdentical.setText("Enter two strings. The program will output whether or not they are identical.");

        btnIdentical.setText("Identical?");
        btnIdentical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdenticalActionPerformed(evt);
            }
        });

        lblInstIndexOf.setText("Enter a string and a letter. The program will output wether or not the letter is found in the string.");

        btnIndexOf.setText("Letter Found?");
        btnIndexOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndexOfActionPerformed(evt);
            }
        });

        lblInstCharAtMultiple.setText("Enter a string that is at least 8 characters long. The program will output characters four to six.");

        btnCharAtMultiple.setText("Characters 4 to 6");
        btnCharAtMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCharAtMultipleActionPerformed(evt);
            }
        });

        lblInstReplace.setText("Enter a string that contains at least one letter \"a\".The program will replace all occurances of \"a\" with \"x\".");

        btnReplace.setText("Replace");
        btnReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHeader)
                    .addComponent(lblInstLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInstToUpper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLength)
                        .addGap(18, 18, 18)
                        .addComponent(lblLengthValue, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtToUpper, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnToUpper)
                        .addGap(18, 18, 18)
                        .addComponent(lblToUpperValue, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInstCharAt, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCharAt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCharAt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCharAtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInstIdentical, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdentical1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdentical2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIdentical)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIdenticalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIndexOf1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIndexOf2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIndexOf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIndexOfValue, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCharAtMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCharAtMultiple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCharAtMultipleValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReplace)
                        .addGap(18, 18, 18)
                        .addComponent(lblReplaceValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblInstIndexOf, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInstCharAtMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInstReplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstLength)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLength)
                    .addComponent(lblLengthValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstToUpper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtToUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToUpper)
                    .addComponent(lblToUpperValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstCharAt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCharAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharAt)
                    .addComponent(lblCharAtValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstIdentical)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentical1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentical2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIdentical)
                    .addComponent(lblIdenticalValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstIndexOf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIndexOf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIndexOf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIndexOf)
                    .addComponent(lblIndexOfValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstCharAtMultiple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCharAtMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharAtMultiple)
                    .addComponent(lblCharAtMultipleValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstReplace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReplace)
                    .addComponent(lblReplaceValue))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLengthActionPerformed
     String words = txtLength.getText();
     int lengthOfString = 0;
     lengthOfString = words.length();
              lblLengthValue.setText(String.valueOf(lengthOfString));
    }//GEN-LAST:event_btnLengthActionPerformed

    private void btnToUpperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToUpperActionPerformed
       String words = txtToUpper.getText();
     String uppercaseString;
     uppercaseString = words.toUpperCase();
              lblToUpperValue.setText(String.valueOf(uppercaseString));
    }//GEN-LAST:event_btnToUpperActionPerformed

    private void btnCharAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCharAtActionPerformed
        String words = txtCharAt.getText();
     char charAtString;
     charAtString = words.charAt(3);
              lblCharAtValue.setText(String.valueOf(charAtString));
    }//GEN-LAST:event_btnCharAtActionPerformed

    private void btnIdenticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdenticalActionPerformed
    String words1 = txtIdentical1.getText();
    String words2 = txtIdentical2.getText();
    boolean identical;
     identical = words2.equals(words1);
     if (identical != true)
             {
                 lblIdenticalValue.setText(String.valueOf("They are different!"));
             }
     else
     {
    lblIdenticalValue.setText(String.valueOf("They are the same!"));
     }
    }//GEN-LAST:event_btnIdenticalActionPerformed

    private void btnIndexOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndexOfActionPerformed
        String words1 = txtIndexOf1.getText();
    String words2 = txtIndexOf2.getText();
    boolean contains;
     contains = words1.contains(words2);
     if (contains != true)
             {
                 lblIndexOfValue.setText(String.valueOf("The letter is not in the string."));
             }
     else
     {
    lblIndexOfValue.setText(String.valueOf("The letter is in the string."));
     }
    }//GEN-LAST:event_btnIndexOfActionPerformed

    private void btnCharAtMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCharAtMultipleActionPerformed
        String words = txtCharAtMultiple.getText();
     char charAt4;
     char charAt6;
     charAt4 = words.charAt(3);
         charAt6 = words.charAt(5);
              lblCharAtMultipleValue.setText(String.valueOf(charAt4)+(charAt6));
    }//GEN-LAST:event_btnCharAtMultipleActionPerformed

    private void btnReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplaceActionPerformed
    String words = txtReplace.getText();
 String replacedString;
     replacedString = words.replace("a","x");
              lblReplaceValue.setText(String.valueOf(replacedString));
    }//GEN-LAST:event_btnReplaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsingStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsingStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsingStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsingStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsingStringMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCharAt;
    private javax.swing.JButton btnCharAtMultiple;
    private javax.swing.JButton btnIdentical;
    private javax.swing.JButton btnIndexOf;
    private javax.swing.JButton btnLength;
    private javax.swing.JButton btnReplace;
    private javax.swing.JButton btnToUpper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCharAtMultipleValue;
    private javax.swing.JLabel lblCharAtValue;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblIdenticalValue;
    private javax.swing.JLabel lblIndexOfValue;
    private javax.swing.JLabel lblInstCharAt;
    private javax.swing.JLabel lblInstCharAtMultiple;
    private javax.swing.JLabel lblInstIdentical;
    private javax.swing.JLabel lblInstIndexOf;
    private javax.swing.JLabel lblInstLength;
    private javax.swing.JLabel lblInstReplace;
    private javax.swing.JLabel lblInstToUpper;
    private javax.swing.JLabel lblLengthValue;
    private javax.swing.JLabel lblReplaceValue;
    private javax.swing.JLabel lblToUpperValue;
    private javax.swing.JTextField txtCharAt;
    private javax.swing.JTextField txtCharAtMultiple;
    private javax.swing.JTextField txtIdentical1;
    private javax.swing.JTextField txtIdentical2;
    private javax.swing.JTextField txtIndexOf1;
    private javax.swing.JTextField txtIndexOf2;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtReplace;
    private javax.swing.JTextField txtToUpper;
    // End of variables declaration//GEN-END:variables
}
